### ISSUE TITLE
Crash on widget deny premission

### ISSUE THREAD

**Issue by quaap** [quaap/LaunchTime#4]
If you create a widget which asks for permission and you deny it, you may receive a crash like the one below.  If you receive a crash like this, please let me know which widget you were adding.

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=5645, result=0, data=null} to activity {com.quaap.launchtime/com.quaap.launchtime.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4058)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4101)
	at android.app.ActivityThread.access$1400(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1497)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
	at com.quaap.launchtime.widgets.Widget.onActivityResult(Widget.java:213)
	at com.quaap.launchtime.MainActivity.onActivityResult(MainActivity.java:1334)

**Comment by mase76** [comment]
Yes, I also got this crash with the digital clock and the fairphone all apps widget. Did not try more, as I permitted the widget creation  Seems to be with every widget.

**Comment by just-Nob** [comment]
The same with me.
Doesn't seem to matter which widget I'm trying to add. After the crash report, LaunchTime restarts with the permission request again, so there's no other escape from it but granting them or reinstalling the app... ;) 
You should have got a crash report from my device.

**Comment by just-Nob** [comment]
Sorry... - hadn't recognized that it should be fixed in current version.
I just installed v.0.2 and the crash arms to be gone.
But now, sometimes a permission request appears without any obvious reason... - I'll keep an eye on it.

Anyway, where does a widget appear if permission is granted?

**Comment by just-Nob** [comment]
It seems to me that my tries of adding widgets result in empty tiles.

See #13 "Empty tiles in some categories app lists".
